/*
 * Module: EXT-Saint
 * @bugsounet
 * 2hdlockness
 */

const NodeHelper = require("node_helper");

var log = () => { /* do nothing */ };

module.exports = NodeHelper.create({
  start () {
    console.log("[SAINT] EXT-Saint Version:", require("./package.json").version);
    this.Saint = new Array();
    for (var i = 1; i <= 31; i++) this.Saint[i] = new Array();

    /** this.Saint[jour][mois] = "Nom du this.Saint" **/
    this.Saint[1][1] = "Jour de l'an";
    this.Saint[1][2] = "Sainte Ella";
    this.Saint[1][3] = "Saint Aubin";
    this.Saint[1][4] = "Saint Hugues";
    this.Saint[1][5] = "Saint Jeremie";
    this.Saint[1][6] = "Saint Justin";
    this.Saint[1][7] = "Saint Thierry";
    this.Saint[1][8] = "Saint Alphonse";
    this.Saint[1][9] = "Saint Gilles";
    this.Saint[1][10] = "Sainte Thérèse";
    this.Saint[1][11] = "Tousthis.Saint";
    this.Saint[1][12] = "Sainte Florence";
    this.Saint[2][1] = "Saint Basile";
    this.Saint[2][2] = "Saint Théophane";
    this.Saint[2][3] = "Saint Jaouen";
    this.Saint[2][4] = "Sainte Sandrine";
    this.Saint[2][5] = "Saint Boris";
    this.Saint[2][6] = "Sainte Blandine";
    this.Saint[2][7] = "Saint Martinien";
    this.Saint[2][8] = "Saint Julien";
    this.Saint[2][9] = "Sainte Ingrid";
    this.Saint[2][10] = "Saint Léger";
    this.Saint[2][11] = "Défunts";
    this.Saint[2][12] = "Sainte Viviane";
    this.Saint[3][1] = "Sainte Geneviève";
    this.Saint[3][2] = "Saint Blaise";
    this.Saint[3][3] = "Saint Gwénola";
    this.Saint[3][4] = "Saint Richard";
    this.Saint[3][5] = "Saint Philippe";
    this.Saint[3][6] = "Saint Kevin";
    this.Saint[3][7] = "Saint Thomas";
    this.Saint[3][8] = "Sainte Lydie";
    this.Saint[3][9] = "Saint Grégoire";
    this.Saint[3][10] = "Saint Gérard";
    this.Saint[3][11] = "Saint Hubert";
    this.Saint[3][12] = "Saint Xavier";
    this.Saint[4][1] = "Saint Odilon";
    this.Saint[4][2] = "Sainte Véronique";
    this.Saint[4][3] = "Saint Casimir";
    this.Saint[4][4] = "Saint Isidore";
    this.Saint[4][5] = "Saint Sylvain";
    this.Saint[4][6] = "Sainte Clotilde";
    this.Saint[4][7] = "Saint Florent";
    this.Saint[4][8] = "Saint Jean-Marie";
    this.Saint[4][9] = "Sainte Rosalie";
    this.Saint[4][10] = "Saint François";
    this.Saint[4][11] = "Saint Charles";
    this.Saint[4][12] = "Sainte Barbara";
    this.Saint[5][1] = "Saint Edouard";
    this.Saint[5][2] = "Sainte Agathe";
    this.Saint[5][3] = "Saint Olive";
    this.Saint[5][4] = "Sainte Irène";
    this.Saint[5][5] = "Sainte Judith";
    this.Saint[5][6] = "Saint Igor";
    this.Saint[5][7] = "Saint Antoine";
    this.Saint[5][8] = "Saint Abel";
    this.Saint[5][9] = "Sainte Raïssa";
    this.Saint[5][10] = "Sainte Fleur";
    this.Saint[5][11] = "Sainte Sylvie";
    this.Saint[5][12] = "Saint Gérald";
    this.Saint[6][1] = "Sainte Mélaine";
    this.Saint[6][2] = "Saint Gaston";
    this.Saint[6][3] = "Sainte Colette";
    this.Saint[6][4] = "Saint Marcellin";
    this.Saint[6][5] = "Sainte Prudence";
    this.Saint[6][6] = "Saint Norbert";
    this.Saint[6][7] = "Sainte Mariette";
    this.Saint[6][8] = "Saint Octavien";
    this.Saint[6][9] = "Saint Bertrand";
    this.Saint[6][10] = "Saint Bruno";
    this.Saint[6][11] = "Sainte Bertille";
    this.Saint[6][12] = "Saint Nicolas";
    this.Saint[7][1] = "Saint Raymond";
    this.Saint[7][2] = "Sainte Eugénie";
    this.Saint[7][3] = "Sainte Félicité";
    this.Saint[7][4] = "Saint Jean-Baptiste";
    this.Saint[7][5] = "Sainte Gisèle";
    this.Saint[7][6] = "Saint Gilbert";
    this.Saint[7][7] = "Saint Eliane";
    this.Saint[7][8] = "Saint Gaétan";
    this.Saint[7][9] = "Sainte Reine";
    this.Saint[7][10] = "Saint Serge";
    this.Saint[7][11] = "Sainte Carine";
    this.Saint[7][12] = "Saint Ambroise";
    this.Saint[8][1] = "Saint Lucien";
    this.Saint[8][2] = "Sainte Jacqueline";
    this.Saint[8][3] = "Saint Jean de Dieu";
    this.Saint[8][4] = "Sainte Julie";
    this.Saint[8][5] = "Saint Désiré";
    this.Saint[8][6] = "Saint Médard";
    this.Saint[8][7] = "Saint Thibaud";
    this.Saint[8][8] = "Saint Dominique";
    this.Saint[8][9] = "Saint Adrien";
    this.Saint[8][10] = "Sainte Pélagie";
    this.Saint[8][11] = "Saint Geoffroy";
    this.Saint[8][12] = "Sainte Frida";
    this.Saint[9][1] = "Sainte Alix";
    this.Saint[9][2] = "Sainte Apolline";
    this.Saint[9][3] = "Sainte Françoise";
    this.Saint[9][4] = "Saint Gautier";
    this.Saint[9][5] = "Sainte Pacôme";
    this.Saint[9][6] = "Sainte Diane";
    this.Saint[9][7] = "Sainte Amandine";
    this.Saint[9][8] = "Saint Amour";
    this.Saint[9][9] = "Saint Alain";
    this.Saint[9][10] = "Saint Denis";
    this.Saint[9][11] = "Saint Théodore";
    this.Saint[9][12] = "Saint Pierre Fourier";
    this.Saint[10][1] = "Saint Guillaume";
    this.Saint[10][2] = "Saint Arnaud";
    this.Saint[10][3] = "Saint Vivien";
    this.Saint[10][4] = "Saint Fulbert";
    this.Saint[10][5] = "Sainte Solange";
    this.Saint[10][6] = "Sainte Trinité";
    this.Saint[10][7] = "Saint Ulric";
    this.Saint[10][8] = "Saint Laurent";
    this.Saint[10][9] = "Sainte Inès";
    this.Saint[10][10] = "Saint Ghislain";
    this.Saint[10][11] = "Saint Léon";
    this.Saint[10][12] = "Saint Romaric";
    this.Saint[11][1] = "Saint Paulin";
    this.Saint[11][2] = "ND de Lourdes";
    this.Saint[11][3] = "Sainte Rosine";
    this.Saint[11][4] = "Saint Stanislas";
    this.Saint[11][5] = "Sainte Estelle";
    this.Saint[11][6] = "Saint Barnabé";
    this.Saint[11][7] = "Saint Benoît";
    this.Saint[11][8] = "Sainte Claire";
    this.Saint[11][9] = "Saint Adelphe";
    this.Saint[11][10] = "Saint Firmin";
    this.Saint[11][11] = "Saint Martin";
    this.Saint[11][12] = "Saint Daniel";
    this.Saint[12][1] = "Sainte Tatiana";
    this.Saint[12][2] = "Saint Félix";
    this.Saint[12][3] = "Sainte Justine";
    this.Saint[12][4] = "Saint Jules";
    this.Saint[12][5] = "Saint Achille";
    this.Saint[12][6] = "Saint Guy";
    this.Saint[12][7] = "Saint Olivier";
    this.Saint[12][8] = "Sainte Clarisse";
    this.Saint[12][9] = "Saint Apollinaire";
    this.Saint[12][10] = "Saint Wilfrid";
    this.Saint[12][11] = "Saint Christian";
    this.Saint[12][12] = "Sainte Chantal";
    this.Saint[13][1] = "Sainte Yvette";
    this.Saint[13][2] = "Sainte Béatrice";
    this.Saint[13][3] = "Saint Rodrigue";
    this.Saint[13][4] = "Sainte Ida";
    this.Saint[13][5] = "Sainte Rolande";
    this.Saint[13][6] = "Saint Antoine";
    this.Saint[13][7] = "Saint Henri - Saint Joël";
    this.Saint[13][8] = "Saint Hippolyte";
    this.Saint[13][9] = "Saint Aimé";
    this.Saint[13][10] = "Saint Géraud";
    this.Saint[13][11] = "Saint Brice";
    this.Saint[13][12] = "Saint Lucie";
    this.Saint[14][1] = "Sainte Nina";
    this.Saint[14][2] = "Saint Valentin";
    this.Saint[14][3] = "Sainte Mathilde";
    this.Saint[14][4] = "Saint Maxime";
    this.Saint[14][5] = "Saint Matthias";
    this.Saint[14][6] = "Saint Elisée";
    this.Saint[14][7] = "Saint Camille - Fête Nationale";
    this.Saint[14][8] = "Saint Evrard";
    this.Saint[14][9] = "Saint Materne";
    this.Saint[14][10] = "Saint Juste";
    this.Saint[14][11] = "Saint Sidoine";
    this.Saint[14][12] = "Sainte Odile";
    this.Saint[15][1] = "Saint Rémi";
    this.Saint[15][2] = "Saint Claude";
    this.Saint[15][3] = "Sainte Louise";
    this.Saint[15][4] = "Saint Paterne";
    this.Saint[15][5] = "Sainte Denise";
    this.Saint[15][6] = "Sainte Germaine";
    this.Saint[15][7] = "Saint Donald";
    this.Saint[15][8] = "Sainte Marie - Assomption";
    this.Saint[15][9] = "Saint Roland";
    this.Saint[15][10] = "Sainte Thérèse";
    this.Saint[15][11] = "Saint Albert";
    this.Saint[15][12] = "Sainte Ninon";
    this.Saint[16][1] = "Saint Marcel";
    this.Saint[16][2] = "Sainte Julienne";
    this.Saint[16][3] = "Sainte Bénédicte";
    this.Saint[16][4] = "Saint Benoît-Joseph";
    this.Saint[16][5] = "Saint Honoré";
    this.Saint[16][6] = "Saint Régis";
    this.Saint[16][7] = "Sainte Carmen";
    this.Saint[16][8] = "Saint Armel";
    this.Saint[16][9] = "Sainte Edith";
    this.Saint[16][10] = "Sainte Edwige";
    this.Saint[16][11] = "Sainte Marguerite";
    this.Saint[16][12] = "Sainte Alice";
    this.Saint[17][1] = "Sainte Roseline";
    this.Saint[17][2] = "Saint Alexis";
    this.Saint[17][3] = "Saint Patrick";
    this.Saint[17][4] = "Saint Anicet";
    this.Saint[17][5] = "Saint Pascal";
    this.Saint[17][6] = "Saint Hervé";
    this.Saint[17][7] = "Sainte Charlotte";
    this.Saint[17][8] = "Saint Hyacinthe";
    this.Saint[17][9] = "Saint Renaud";
    this.Saint[17][10] = "Saint Baudouin";
    this.Saint[17][11] = "Sainte Elisabeth";
    this.Saint[17][12] = "Saint Gaël";
    this.Saint[18][1] = "Sainte Prisca";
    this.Saint[18][2] = "Sainte Bernadette";
    this.Saint[18][3] = "Saint Cyrille";
    this.Saint[18][4] = "Saint Parfait";
    this.Saint[18][5] = "Saint Eric";
    this.Saint[18][6] = "Saint Léonce";
    this.Saint[18][7] = "Saint Frédéric";
    this.Saint[18][8] = "Sainte Hélène";
    this.Saint[18][9] = "Sainte Nadège";
    this.Saint[18][10] = "Saint Luc";
    this.Saint[18][11] = "Sainte Aude";
    this.Saint[18][12] = "Saint Gatien";
    this.Saint[19][1] = "Saint Marius";
    this.Saint[19][2] = "Saint Gabin";
    this.Saint[19][3] = "Saint Joseph";
    this.Saint[19][4] = "Sainte Emma";
    this.Saint[19][5] = "Saint Yves";
    this.Saint[19][6] = "Saint Romuald";
    this.Saint[19][7] = "Saint Arsène";
    this.Saint[19][8] = "Saint Jean-Eudes";
    this.Saint[19][9] = "Sainte Emilie";
    this.Saint[19][10] = "Saint René Goupil";
    this.Saint[19][11] = "Saint Tanguy";
    this.Saint[19][12] = "Saint Urbain";
    this.Saint[20][1] = "Saint Sébastien";
    this.Saint[20][2] = "Sainte Aimée";
    this.Saint[20][3] = "Saint Herbert";
    this.Saint[20][4] = "Sainte Odette";
    this.Saint[20][5] = "Saint Bernardin";
    this.Saint[20][6] = "Saint Silvère";
    this.Saint[20][7] = "Sainte Marina";
    this.Saint[20][8] = "Saint Bernard";
    this.Saint[20][9] = "Saint Davy";
    this.Saint[20][10] = "Sainte Adeline";
    this.Saint[20][11] = "Saint Edmond";
    this.Saint[20][12] = "Saint Théophile";
    this.Saint[21][1] = "Sainte Agnès";
    this.Saint[21][2] = "Saint Damien";
    this.Saint[21][3] = "Sainte Clémence";
    this.Saint[21][4] = "Saint Anselme";
    this.Saint[21][5] = "Saint Constantin";
    this.Saint[21][6] = "Saint Rodolphe";
    this.Saint[21][7] = "Saint Victor";
    this.Saint[21][8] = "Saint Christophe";
    this.Saint[21][9] = "Saint Matthieu";
    this.Saint[21][10] = "Sainte Céline";
    this.Saint[21][11] = "Présentation de Marie";
    this.Saint[21][12] = "Saint Pierre Canisius";
    this.Saint[22][1] = "Saint Vincent";
    this.Saint[22][2] = "Sainte Isabelle";
    this.Saint[22][3] = "Sainte Léa";
    this.Saint[22][4] = "Saint Alexandre";
    this.Saint[22][5] = "Saint Emile";
    this.Saint[22][6] = "Saint Alban";
    this.Saint[22][7] = "Sainte Marie-Madeleine";
    this.Saint[22][8] = "Saint Fabrice";
    this.Saint[22][9] = "Saint Maurice";
    this.Saint[22][10] = "Sainte Elodie";
    this.Saint[22][11] = "Sainte Cécile";
    this.Saint[22][12] = "Sainte Françoise-Xavière";
    this.Saint[23][1] = "Saint Barnard";
    this.Saint[23][2] = "Saint Lazare";
    this.Saint[23][3] = "Saint Victorien";
    this.Saint[23][4] = "Saint Georges";
    this.Saint[23][5] = "Saint Didier";
    this.Saint[23][6] = "Sainte Audrey";
    this.Saint[23][7] = "Sainte Brigitte";
    this.Saint[23][8] = "Sainte Rose";
    this.Saint[23][9] = "Saint Constant";
    this.Saint[23][10] = "Saint Jean de Capistran";
    this.Saint[23][11] = "Saint Clément";
    this.Saint[23][12] = "Saint Armand";
    this.Saint[24][1] = "Saint François de Sales";
    this.Saint[24][2] = "Saint Modeste";
    this.Saint[24][3] = "Sainte Catherine";
    this.Saint[24][4] = "Saint Fidèle";
    this.Saint[24][5] = "Saint Donatien";
    this.Saint[24][6] = "Saint Yann";
    this.Saint[24][7] = "Sainte Christine";
    this.Saint[24][8] = "Saint Barthélémy";
    this.Saint[24][9] = "Sainte Thècle";
    this.Saint[24][10] = "Saint Florentin";
    this.Saint[24][11] = "Sainte Flora";
    this.Saint[24][12] = "Sainte Adèle";
    this.Saint[25][1] = "Saint Apollos";
    this.Saint[25][2] = "Saint Roméo";
    this.Saint[25][3] = "Annonciation";
    this.Saint[25][4] = "Saint Marc";
    this.Saint[25][5] = "Sainte Sophie";
    this.Saint[25][6] = "Saint Prosper";
    this.Saint[25][7] = "Saint Jacques";
    this.Saint[25][8] = "Saint Louis";
    this.Saint[25][9] = "Saint Hermann";
    this.Saint[25][10] = "Saint Crépin";
    this.Saint[25][11] = "Sainte Catherine";
    this.Saint[25][12] = "Noël";
    this.Saint[26][1] = "Sainte Paule";
    this.Saint[26][2] = "Saint Nestor";
    this.Saint[26][3] = "Sainte Lara";
    this.Saint[26][4] = "Sainte Alida";
    this.Saint[26][5] = "Saint Bérenger";
    this.Saint[26][6] = "Saint Anthelme";
    this.Saint[26][7] = "Sainte Anne";
    this.Saint[26][8] = "Sainte Natacha";
    this.Saint[26][9] = "Saint Côme - Saint Damien";
    this.Saint[26][10] = "Saint Dimitri";
    this.Saint[26][11] = "Sainte Delphine";
    this.Saint[26][12] = "Saint Etienne";
    this.Saint[27][1] = "Sainte Angèle";
    this.Saint[27][2] = "Sainte Honorine";
    this.Saint[27][3] = "Saint Habib";
    this.Saint[27][4] = "Sainte Zita";
    this.Saint[27][5] = "Saint Augustin";
    this.Saint[27][6] = "Saint Fernand";
    this.Saint[27][7] = "Sainte Nathalie";
    this.Saint[27][8] = "Sainte Monique";
    this.Saint[27][9] = "Saint Vincent de Paul";
    this.Saint[27][10] = "Sainte Emeline";
    this.Saint[27][11] = "Saint Séverin";
    this.Saint[27][12] = "Saint Jean";
    this.Saint[28][1] = "Saint Thomas d'Aquin";
    this.Saint[28][2] = "Saint Romain";
    this.Saint[28][3] = "Saint Gontran";
    this.Saint[28][4] = "Sainte Valérie";
    this.Saint[28][5] = "Saint Germain";
    this.Saint[28][6] = "Saint Irénée";
    this.Saint[28][7] = "Saint Samson";
    this.Saint[28][8] = "Saint Augustin";
    this.Saint[28][9] = "Saint Venceslas";
    this.Saint[28][10] = "Saint Simon";
    this.Saint[28][11] = "Saint Jacques de la Marche";
    this.Saint[28][12] = "Saint Gaspard";
    this.Saint[29][1] = "Saint Gildas";
    this.Saint[29][2] = "Saint Auguste";
    this.Saint[29][3] = "Sainte Gwladys";
    this.Saint[29][4] = "Sainte Catherine";
    this.Saint[29][5] = "Saint Aymard";
    this.Saint[29][6] = "Saint Pierre - Saint Paul";
    this.Saint[29][7] = "Sainte Marthe";
    this.Saint[29][8] = "Sainte Sabine";
    this.Saint[29][9] = "Saints Michel";
    this.Saint[29][10] = "Saint Narcisse";
    this.Saint[29][11] = "Saint Saturnin";
    this.Saint[29][12] = "Saint David";
    this.Saint[30][1] = "Sainte Martine";
    this.Saint[30][3] = "Saint Amédée";
    this.Saint[30][4] = "Saint Robert";
    this.Saint[30][5] = "Saint Ferdinand";
    this.Saint[30][6] = "Saint Martial";
    this.Saint[30][7] = "Sainte Juliette";
    this.Saint[30][8] = "Saint Fiacre";
    this.Saint[30][9] = "Saint Jérôme";
    this.Saint[30][10] = "Sainte Bienvenue";
    this.Saint[30][11] = "Saint André";
    this.Saint[30][12] = "Saint Roger";
    this.Saint[31][1] = "Sainte Marcelle";
    this.Saint[31][3] = "Saint Benjamin";
    this.Saint[31][5] = "Sainte Perrette";
    this.Saint[31][7] = "Saint Ignace";
    this.Saint[31][8] = "Saint Aristide";
    this.Saint[31][10] = "Saint Quentin";
    this.Saint[31][12] = "Saint Sylvestre";

    this.DayNow = null;
    this.MonthNow = null;
    this.myDay = null;
    this.DayTomorrow = null;
    this.MonthTomorrow = null;
    this.Data = {
      today: null,
      tomorrow: null
    };
  },

  socketNotificationReceived (notification, payload) {
    switch (notification) {
      case "CONFIG":
        this.config = payload;
        if (this.config.debug) log = (...args) => { console.log("[SAINT]", ...args); };
        log("Config:", this.config);
        this.initialize();
        break;
    }
  },

  initialize () {
    console.log("[SAINT] EXT-Saint Version:", require("./package.json").version, "rev:", require("./package.json").rev);
    this.sendSocketNotification("INITIALIZED");
    this.myDay = new Date(Date.now()).getDate();
    this.getDate();
    this.sendData(this.SaintDuJour());
    this.update();
    console.log("[SAINT] EXT-Saint is now initialized!");
  },

  sendData (data) {
    log("Send Data to module:", data);
    this.sendSocketNotification("DATA", data);
  },

  SaintDuJour () {
    log(`Actual Day: ${this.DayNow}`, `In memory: ${this.myDay}`);
    this.Data.today = this.Saint[this.DayNow][this.MonthNow];
    this.Data.tomorrow = this.Saint[this.DayTomorrow][this.MonthTomorrow];
    log(`Today ${this.DayNow}/${this.MonthNow}:`, this.Data.today);
    log(`Tomorrow ${this.DayTomorrow}/${this.MonthTomorrow}:`, this.Data.tomorrow);

    return this.Data;
  },

  update () {
    setInterval(() => {
      this.getDate();
      if (this.DayNow !== this.myDay) {
        this.sendData(this.SaintDuJour());
        this.myDay = this.DayNow;
        log("Updated!");
      }
    }, this.config.update);
  },

  getDate () {
    var MyDate = new Date(Date.now());
    this.DayNow = MyDate.getDate();
    this.MonthNow = MyDate.getMonth() + 1;
    var Tomorrow = new Date(new Date(Date.now()).setDate(new Date(Date.now()).getDate() + 1));
    this.DayTomorrow = Tomorrow.getDate();
    this.MonthTomorrow = Tomorrow.getMonth() + 1;
  }
});
