name: "ESBuild Testing"

on: [pull_request]

jobs:
  eslint:
    name: Run esbuild
    runs-on: ubuntu-latest
    steps:
      - name: "Use Node.js v23.x (latest)"
        uses: actions/setup-node@v4
        with:
          node-version: "23.x"
          check-latest: true

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm prune

      - name: Run ESBuild MMM-Bugsounet
        run: node installer/minify
        continue-on-error: false

      - name: Run ESBuild EXT-Assistant
        run: node installer/minify --path=EXTs/EXT-Assistant
        continue-on-error: false

      - name: Run ESBuild EXT-Background
        run: node installer/minify --path=EXTs/EXT-Background
        continue-on-error: false

      - name: Run ESBuild EXT-Browser
        run: node installer/minify --path=EXTs/EXT-Browser
        continue-on-error: false

      - name: Run ESBuild EXT-Detector
        run: node installer/minify --path=EXTs/EXT-Detector
        continue-on-error: false

      - name: Run ESBuild EXT-Freebox
        run: node installer/minify --path=EXTs/EXT-Freebox
        continue-on-error: false

      - name: Run ESBuild EXT-FreeboxTV
        run: node installer/minify --path=EXTs/EXT-FreeboxTV
        continue-on-error: false

      - name: Run ESBuild EXT-GooglePhotos
        run: node installer/minify --path=EXTs/EXT-GooglePhotos
        continue-on-error: false

      - name: Run ESBuild EXT-Glassy
        run: node installer/minify --path=EXTs/EXT-Glassy
        continue-on-error: false

      - name: Run ESBuild EXT-Keyboard
        run: node installer/minify --path=EXTs/EXT-Keyboard
        continue-on-error: false

      - name: Run ESBuild EXT-Librespot
        run: node installer/minify --path=EXTs/EXT-Librespot
        continue-on-error: false

      - name: Run ESBuild EXT-MeteoFrance
        run: node installer/minify --path=EXTs/EXT-MeteoFrance
        continue-on-error: false

      - name: Run ESBuild EXT-MusicPlayer
        run: node installer/minify --path=EXTs/EXT-MusicPlayer
        continue-on-error: false

      - name: Run ESBuild EXT-NetatmoThermostat
        run: node installer/minify --path=EXTs/EXT-NetatmoThermostat
        continue-on-error: false

      - name: Run ESBuild EXT-Pages
        run: node installer/minify --path=EXTs/EXT-Pages
        continue-on-error: false

      - name: Run ESBuild EXT-Photos
        run: node installer/minify --path=EXTs/EXT-Photos
        continue-on-error: false

      - name: Run ESBuild EXT-PrixCarburants
        run: node installer/minify --path=EXTs/EXT-PrixCarburants
        continue-on-error: false

      - name: Run ESBuild EXT-RadioPlayer
        run: node installer/minify --path=EXTs/EXT-RadioPlayer
        continue-on-error: false

      - name: Run ESBuild EXT-Saint
        run: node installer/minify --path=EXTs/EXT-Saint
        continue-on-error: false

      - name: Run ESBuild EXT-Screen
        run: node installer/minify --path=EXTs/EXT-Screen
        continue-on-error: false

      - name: Run ESBuild EXT-SmartHome
        run: node installer/minify --path=EXTs/EXT-SmartHome
        continue-on-error: false

      - name: Run ESBuild EXT-Spotify
        run: node installer/minify --path=EXTs/EXT-Spotify
        continue-on-error: false

      - name: Run ESBuild EXT-StreamDeck
        run: node installer/minify --path=EXTs/EXT-StreamDeck
        continue-on-error: false

      - name: Run ESBuild EXT-TelegramBot
        run: node installer/minify --path=EXTs/EXT-TelegramBot
        continue-on-error: false

      - name: Run ESBuild EXT-Touch
        run: node installer/minify --path=EXTs/EXT-Touch
        continue-on-error: false

      - name: Run ESBuild EXT-Updates
        run: node installer/minify --path=EXTs/EXT-Updates
        continue-on-error: false

      - name: Run ESBuild EXT-VLCServer
        run: node installer/minify --path=EXTs/EXT-VLCServer
        continue-on-error: false

      - name: Run ESBuild EXT-Volume
        run: node installer/minify --path=EXTs/EXT-Volume
        continue-on-error: false

      - name: Run ESBuild EXT-YouTube
        run: node installer/minify --path=EXTs/EXT-YouTube
        continue-on-error: false

      - name: Run ESBuild EXT-YouTubeCast
        run: node installer/minify --path=EXTs/EXT-YouTubeCast
        continue-on-error: false

