name: "[Windows] MagicMirror² (master) and MMM-Bugsounet full build Testing"

on: [pull_request]

jobs:
  build:
    name: Test install MMM-Bugsounet
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
    steps:
      - name: "Use Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true

      - name: Checkout MagicMirror²
        uses: actions/checkout@v4
        with:
          repository: MagicMirrorOrg/MagicMirror

      - name: Install MagicMirror²
        run: npm install

      - name: Checkout MMM-Bugsounet
        uses: actions/checkout@v4
        with:
          path: MagicMirror/modules/MMM-Bugsounet

      - name: Install MMM-Bugsounet
        run: npm run setup
        working-directory: MagicMirror/modules/MMM-Bugsounet
        continue-on-error: false

      - name: Run ESBuild EXT-FreeboxTV
        run: npm run setup
        working-directory: MagicMirror/modules/MMM-Bugsounet/EXTs/EXT-FreeboxTV
        continue-on-error: false

      - name: Run ESBuild EXT-Glassy
        run: npm run setup
        working-directory: MagicMirror/modules/MMM-Bugsounet/EXTs/EXT-Glassy
        continue-on-error: false

      - name: Run ESBuild EXT-Librespot
        run: npm run setup
        working-directory: MagicMirror/modules/MMM-Bugsounet/EXTs/EXT-Librespot
        continue-on-error: false

      - name: Run ESBuild EXT-Pages
        run: npm run setup
        working-directory: MagicMirror/modules/MMM-Bugsounet/EXTs/EXT-Pages
        continue-on-error: false

      - name: Run ESBuild EXT-RadioPlayer
        run: npm run setup
        working-directory: MagicMirror/modules/MMM-Bugsounet/EXTs/EXT-RadioPlayer
        continue-on-error: false

      - name: Run ESBuild EXT-Saint
        run: npm run setup
        working-directory: MagicMirror/modules/MMM-Bugsounet/EXTs/EXT-Saint
        continue-on-error: false

      - name: Run ESBuild EXT-Screen
        run: npm run setup
        working-directory: MagicMirror/modules/MMM-Bugsounet/EXTs/EXT-Screen
        continue-on-error: false

      - name: Run ESBuild EXT-Spotify
        run: npm run setup
        working-directory:  MagicMirror/modules/MMM-Bugsounet/EXTs/EXT-Spotify
        continue-on-error: false

      - name: Run ESBuild EXT-TelegramBot
        run: npm run setup
        working-directory: MagicMirror/modules/MMM-Bugsounet/EXTs/EXT-TelegramBot
        continue-on-error: false

      - name: Run ESBuild EXT-Updates
        run: npm run setup
        working-directory: MagicMirror/modules/MMM-Bugsounet/EXTs/EXT-Updates
        continue-on-error: false

      - name: Run ESBuild EXT-VLCServer
        run: npm run setup
        working-directory: MagicMirror/modules/MMM-Bugsounet/EXTs/EXT-VLCServer
        continue-on-error: false

      - name: Run ESBuild EXT-Volume
        run: npm run setup
        working-directory: MagicMirror/modules/MMM-Bugsounet/EXTs/EXT-Volume
        continue-on-error: false

      - name: Run ESBuild EXT-Website
        run: npm run setup
        working-directory: MagicMirror/modules/MMM-Bugsounet/EXTs/EXT-Website
        continue-on-error: false

      - name: Run ESBuild EXT-YouTubeCast
        run: npm run setup
        working-directory: MagicMirror/modules/MMM-Bugsounet/EXTs/EXT-YouTubeCast
        continue-on-error: false
